version: "3.9"

services:
  authdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_TESTER_PASSWORD: 14642163Aa
    volumes:
      - ./volumes/AuthDB:/var/opt/mssql/data

  inventorydb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_TESTER_PASSWORD: 14642163Aa
    volumes:
      - ./volumes/InventoryDB:/var/opt/mssql/data

  paymentdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1435:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_TESTER_PASSWORD: 14642163Aa
    volumes: 
      - ./volumes/PaymentDB:/var/opt/mssql/data

  authservice:
    image: authservice
    restart: always
    ports:
      - 3000:80
    depends_on:
      - authdb

  inventoryservice:
    image: inventoryservice
    restart: always
    ports:
      - 3001:80
      - 3005:123
    depends_on:
      - inventorydb

  paymentservice:
    image: paymentservice
    restart: always
    ports:
      - 3002:80
    depends_on:
      - paymentdb
